### ISSUE TITLE
Cinema 4D R23

### ISSUE THREAD

**Issue by VitalSkib** [safina3d/c4d-random-vertex-color#1]
Hello. 
Any news on Cinema 4D R23 compatibility?

**Comment by safina3d** [comment]
Done!

**Comment by VitalSkib** [comment]
Thanks!

**Comment by VitalSkib** [comment]
Oops, man sorry, I somehow got confused and posted here, although I wanted to write about the Random Color plugin.
I'll write there if you don't mind.

**Comment by safina3d** [comment]
No problem ;)
